language: php
php:
    - "7.0"

services:
    - rabbitmq

addons:
    apt:
        sources:
            - deadsnakes
        packages:
            - python3.5

env:
    global:
        - CELERY_BROKER=localhost
        - MAIL_FROM=noreply@example.com
        - SMTP_HOST=localhost
        - SMTP_PORT=1025
        - SMTP_USER=badger
        - SMTP_PASS=naspw

before_install:
    # We need Python for server and client
    - curl https://bootstrap.pypa.io/get-pip.py | python3.5 - --user
    - pip3.5 install --user -r requirements.txt

    # We need node for Maildev
    - nvm install 5.6
    - npm install -g maildev

before_script:
    - maildev --incoming-user badger --incoming-pass naspw &
    - celery -A mailmq.server worker &
    - echo "sendmail_path = \"python3.5 -m mailmq.client -t\"" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit tests
