version: '2'

services:

    consumer:
        build: .

        links:
            - amqp
            - mail

        volumes:
            - ".:/app"

        environment:
            CELERY_BROKER: amqp
            MAIL_FROM: noreply@example.com
            SMTP_HOST: mail
            SMTP_USER: badger
            SMTP_PASS: naspw

    amqp:
        image: rabbitmq
        ports:
            - "5672:5672"

    mail:
        image: djfarrelly/maildev
        command: bin/maildev --web 80 --smtp 25 --incoming-user badger --incoming-pass naspw
        ports:
            - "80:80"
